openapi: 3.0.0
info:
  title: Malicious Website Detector API
  version: 1.0.0
servers:
  - url: http://localhost:8088
    description: Localhost server
paths:
  /bloomfilter/add:
    post:
      summary: Add a malicious website to the Bloom Filter
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: string
      responses:
        '201':
          description: Website added to the Bloom Filter successfully
        '500':
          description: Internal server error
  /bloomfilter/check:
    get:
      summary: Check if a website is likely malicious
      parameters:
        - in: query
          name: website
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Message indicating the website's maliciousness
          content:
            application/json:
              schema:
                type: string
              examples:
                NotMalicious:
                  value: "The website 'benign1.com' is not malicious."
                Malicious:
                  value: "The website 'malicious1.com' is likely malicious."
        '500':
          description: Internal server error
