openapi: 3.0.0
info:
  title: Malicious Website Detector API
  version: 1.0.0
servers:
  - url: http://localhost:8088
    description: Localhost server
paths:
  /bloomfilter/add:
    post:
      summary: Add a website to the Bloom Filter
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: string
      responses:
        '200':
          description: Success
  /bloomfilter/check:
    get:
      summary: Check if a website is likely malicious
      parameters:
        - in: query
          name: website
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: boolean
